version: '3.7'
services:
  licensingservice:
    image: maxgroup/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "configserver"
networks:
  backend:
    driver: bridge
